-- Commented out because its depreciated
--
--
--
--
--
---- ~/.config/nvim/lua/plugins/configs/lspconfig.lua
--
---- Import the new LSP framework
--local lspconfig = vim.lsp.config
--
---- Common capabilities and on_attach
--local capabilities = vim.lsp.protocol.make_client_capabilities()
--local on_attach = function(client, bufnr)
--  -- Example keymaps
--  local opts = { buffer = bufnr, noremap = true, silent = true }
--  vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
--  vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
--  vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, opts)
--end
--
---- Rust
--lspconfig.rust_analyzer.setup({
--  on_attach = on_attach,
--  capabilities = capabilities,
--  filetypes = { "rust" },
--  root_dir = vim.fs.dirname(vim.fs.find({ "Cargo.toml" }, { upward = true })[1]),
--  settings = {
--    ["rust-analyzer"] = {
--      cargo = { allFeatures = true },
--      checkOnSave = { command = "clippy" },
--    },
--  },
--})
--
---- Lua
--lspconfig.lua_ls.setup({
--  on_attach = on_attach,
--  capabilities = capabilities,
--  settings = {
--    Lua = {
--      diagnostics = { globals = { "vim" } },
--      workspace = { checkThirdParty = false },
--    },
--  },
--})
--
---- Python
--lspconfig.pyright.setup({
--  on_attach = on_attach,
--  capabilities = capabilities,
--})
--
